#!/usr/bin/env python

import os
import sys

def main():
    tango_home = os.environ["TANGO_HOME"]
    path =  tango_home + "/ds/python/PySerial"
    sys.path.insert(0,path)
    import PySerial
    PySerial.main(sys.argv)

if __name__ == "__main__":
    main()
